### ISSUE TITLE
FPGA reconfiguration function?

### ISSUE THREAD

**Issue by szekany** [archntu/dyract#1]
Hi, I'm interested in using Dyract for a partial reconfiguration project, but I've encountered a problem: I looked in the sw/userlib folder for the fpga_reconfig() function, but it doesn't seem to be implemented in any of the header files. Am I missing something?

**Comment by vipinkmenon** [comment]
Hi,
   Thank you for your interest. I forgot to add that function. It is nothing but a wrapper function to fpga_send_data() with ICAP as the target. I have updated the git. Please do check. You just have to specify the .bin file location as the function argument.

**Comment by szekany** [comment]
Awesome, thanks!
